let start = document.querySelector('#start'),
    resultTable = document.querySelector('.result-table'),
    values = resultTable.querySelectorAll('[class$="-value"]'),
    expensesItems = document.querySelectorAll('.expenses-item'),
    btns = document.getElementsByTagName('button'),
    expensesItemBtn = btns[0],
    optionalexpensesBtn = btns[1],
    countBudgetBtn = btns[2],
    optionalexpensesItems = document.querySelectorAll('.optionalexpenses-item'),
    chooseIncome = document.querySelector('.choose-income'),
    checksaving = document.querySelector('#savings'),
    chooseSum = document.querySelector('.choose-sum'),
    choosePercent = document.querySelector('.choose-percent'),
    yearValue  = document.querySelector('.year-value'),
    monthValue  = document.querySelector('.month-value'),
    dayValue  = document.querySelector('.day-value');
